#ifndef ANM_HANDLER_H
#define ANM_HANDLER_H

#define ALL_LEDS_SIZE sizeof(uint32_t) * RGB_DRIVER_COUNT

#define FRAMERATE_FPS 120
#define INTERVAL_US_PER_FRAME (1000000/FRAMERATE_FPS)
#define FADE_LENGTH_MS 350
#define FADE_LENGTH_FRAMES ((FADE_LENGTH_MS*1000) / INTERVAL_US_PER_FRAME)
#define FADE_STEP_FLOAT (float) (1.0f / FADE_LENGTH_FRAMES)

#endif